name: 'Bug Report'
description: 'File a bug report'
body:
  - type: 'markdown'
    attributes:
      value: |
        Thanks for creating an issue 😄!

        Please search open/closed issues before submitting. Someone
        might have asked the same thing before 😉!

        To help us understand your issue better, please fill out the template below.
  - type: 'textarea'
    id: 'description'
    attributes:
      label: 'Description'
      description: 'A brief description of the issue.'
      placeholder: |
        When I ____, I expected ____ to happen but ____ happened instead.
    validations:
      required: true
  - type: 'input'
    id: 'reproduction'
    attributes:
      label: 'Link to Reproduction'
      description: |
        # A link to a CodeSandbox reproduction which demonstrates the bug (Example template:
        # https://codesandbox.io/p/sandbox/snaps-ui-reproduction-starter-7x2cjl )
      placeholder: 'https://codesandbox.io/'
    validations:
      required: false
  - type: 'textarea'
    id: 'steps'
    attributes:
      label: 'Steps to reproduce'
      description: |
        Explain how to cause the issue in the provided reproduction.
      value: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
  - type: 'input'
    id: 'snaps-ui-version'
    attributes:
      label: 'Jc UI Version'
      description: 'The version of Jc UI you use.'
      placeholder: '1.x.x'
    validations:
      required: true
  - type: 'input'
    id: 'chakra-ui-version'
    attributes:
      label: 'Chakra UI Version'
      description: 'The version of Chakra UI you use.'
      placeholder: '2.x.x'
    validations:
      required: false
  - type: 'input'
    id: 'browser'
    attributes:
      label: 'Browser'
      description: 'The browser(s) this issue occurred with.'
      placeholder: 'Google Chrome 93'
  - type: 'checkboxes'
    id: 'operating-system'
    attributes:
      label: 'Operating System'
      description: 'The operating system(s) this issue occurred with.'
      options:
        - label: 'macOS'
        - label: 'Windows'
        - label: 'Linux'
  - type: 'textarea'
    id: 'additional-information'
    attributes:
      label: 'Additional Information'
      description: |
        Use this section to provide any additional information you might have
        like screenshots, notes, or links to ideas.